# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/C3. Convert to FP16.ipynb.

# %% auto 0
__all__ = ['convert_model']

# %% ../nbs/C3. Convert to FP16.ipynb 1
import torch
from pathlib import Path
from fastcore.script import call_parse

from whisperspeech.s2a_delar_mup_wds_mlang import SADelARTransformer
from whisperspeech.t2s_up_wds_mlang_enclm import TSARTransformer

# %% ../nbs/C3. Convert to FP16.ipynb 2
@call_parse
def convert_model(fname:Path, output:Path):
    spec = torch.load(fname)
    if 'speaker_map' in spec['config']:
        model = SADelARTransformer.load_model(spec=spec)
    else:
        model = TSARTransformer.load_model(spec=spec)
    model.switch_dtypes(torch.float16)
    model.save_model(output)
