# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/Calculate emotionality.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/Calculate emotionality.ipynb 1
import webdataset as wds
from whisperspeech import utils
from fastcore.script import call_parse
import numpy as np
from pathlib import Path
import itertools

# %% ../nbs/Calculate emotionality.ipynb 10
@call_parse
def main(shard:Path):
    ds = wds.WebDataset(str(shard)).decode()
    dl = wds.WebLoader(ds, batch_size=None, num_workers=1)
    emotionality = np.concatenate([x['emotions.npy'] for x in itertools.islice(ds, 5000)]).std(0).mean()
    print(f"{emotionality:.2f} {shard.name}")
