# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/C4. Random access to segmented audio files.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/C4. Random access to segmented audio files.ipynb 1
import hashlib
import urllib.parse

# %% ../nbs/C4. Random access to segmented audio files.ipynb 2
def audio_segment_fname(sample=None, dataset=None, key=None):
    if sample is not None:
        key = sample['__key__']
        dataset = sample['__url__'].split('/')[-3]
    hash = hashlib.sha256()
    hash.update(dataset.encode())
    hash.update(key.encode())
    bucket = hash.hexdigest()[:3]
    return f"{dataset}/{bucket}/{key.strip('/.').replace('/', '_')}.m4a"

def audio_segment_url(**kwargs):
    return "https://storage.googleapis.com/etts-audio-chunks/"+urllib.parse.quote(audio_segment_fname(**kwargs))
